POST http://localhost:3333/audio/28ba0db6-c02e-4b47-b211-41481e77b476/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, ddd"
}

### Criar um novo usuário
POST  https://f3e6f88c162aa0b172159baff88c5b0b.serveo.net/users
Content-Type: application/json

{
  "name": "Lorrys",
  "email": "lorryscode@gmail.com",
  "password": "lorrys123",
  "class": "13ª",
  "photoUrl": "https://avatars.githubusercontent.com/u/149355093?s=400&u=f4120a2dacabd8857b74f39ade676d013d2809cc&v=4"
}

###

POST https://1c77848acddb60f7f12e32a2224dbdf1.serveo.net/users/auth
Content-Type: application/json

{
  "email": "plamedisala@gmail.com",
  "password": "plamedi123"
}

###

GET http://localhost:3333/users/50966be6-b75e-4da9-9545-576450b959d8

###

PUT http://localhost:3333/users/50966be6-b75e-4da9-9545-576450b959d8
Content-Type: application/json

{
  "name": "Nome Atualizado",
  "class": "12ª"
}

###

PUT http://localhost:3333/users/50966be6-b75e-4da9-9545-576450b959d8
Content-Type: application/json

{
  "password": "novaSenha456"
}

###

DELETE http://localhost:3333/users/50966be6-b75e-4da9-9545-576450b959d8